### ISSUE TITLE
Realtek high definition audio(sst) Driver

### ISSUE THREAD

**Issue by moutasem1989** [infernix/samsung_tabpro_s#5]
Is there a Linux driver for realtek high definition audio(sst)?
[Here ](https://airbornesurfer.com/2015/04/how-to-install-realtek-hd-audio-driver-in-linux/)there is a methos to install the Drivere but the link they provide is not working. Maybe someone can play aound with the [Native Sound Manager](https://www.chromestory.com/2011/05/how-to-access-chromebooks-native-sounds-manager-alsamixer/)
The device ID is: INTELAUDIO\FUNC_01&VEN_10EC&DEV_0298&SUBSYS_144DC135

**Comment by infernix** [comment]
see https://bugzilla.kernel.org/show_bug.cgi?id=188411 - driver works, headphones too, but no speaker output.

**Comment by moutasem1989** [comment]
I have seen it with no Bugfix in sight !
